# A list of 500 players' names and tags with the master rank ("https://www.op.gg/leaderboards/tier?type=ladder-flex&tier=master&page=1")

summoner_name_list = [
    {"name": "GATES OF OLYMPUS", "tag": "222"},
    {"name": "Exodess", "tag": "G59"},
    {"name": "Love The Streets", "tag": "OTF"},
    {"name": "Kité Machiné", "tag": "EUNE"},
    {"name": "PriestAndKid", "tag": "EUNE"},
    {"name": "PROBLEMζ", "tag": "PRO"},
    {"name": "Azza ツ", "tag": "meow"},
    {"name": "Quess81", "tag": "EUNE"},
    {"name": "Tabakera", "tag": "EUNE"},
    {"name": "iNafferss", "tag": "vittu"},
    {"name": "LilCrownz", "tag": "Eune"},
    {"name": "Agiłity", "tag": "EUNE"},
    {"name": "Cristi VM", "tag": "BEST"},
    {"name": "budyn", "tag": "JDJD"},
    {"name": "zerisia paulinki", "tag": "essa"},
    {"name": "Fheder", "tag": "EUNE"},
    {"name": "Sealed", "tag": "EUNE"},
    {"name": "Lettu", "tag": "EUNE"},
    {"name": "dziamdziam321", "tag": "EUNE"},
    {"name": "PSL Touzas", "tag": "7061"},
    {"name": "shaco", "tag": "pain"},
    {"name": "Milanomia", "tag": "EUNE"},
    {"name": "koca", "tag": "1312"},
    {"name": "AdmiralMuha", "tag": "EUNE"},
    {"name": "Shii No Tenshi", "tag": "EUNE"},
    {"name": "Leonardo123", "tag": "EUNE"},
    {"name": "LuxOn", "tag": "LXON"},
    {"name": "Orcus", "tag": "EUNE"},
    {"name": "Twelve", "tag": "pain"},
    {"name": "dogs enjoyer", "tag": "EUNE"},
    {"name": "LuSaiX", "tag": "2137"},
    {"name": "ƒuma", "tag": "EUNE"},
    {"name": "Dombasek", "tag": "EUNE"},
    {"name": "DR Light", "tag": "1051"},
    {"name": "Teemo Enjoyer", "tag": "QUTAS"},
    {"name": "Horso4", "tag": "EUNE"},
    {"name": "Mike", "tag": "dev"},
    {"name": "BEHEADER", "tag": "NIXU"},
    {"name": "Dava", "tag": "EUNE"},
    {"name": "muruj dziure", "tag": "EUNE"},
    {"name": "Manti", "tag": "Panpi"},
    {"name": "一ノ瀬千鶴は私のワイフです", "tag": "カズヤ"},
    {"name": "CosminThunde", "tag": "EUNE"},
    {"name": "Iura", "tag": "EUNE"},
    {"name": "Δεν θέλω", "tag": "EUNE"},
    {"name": "RPRT", "tag": "RIPRT"},
    {"name": "GamaRade", "tag": "EUNE"},
    {"name": "Venomtear", "tag": "Snake"},
    {"name": "LightMistress", "tag": "EUNE"},
    {"name": "Cae", "tag": "サイコ"},
    {"name": "Charnelli", "tag": "EUNE"},
    {"name": "cute kamis", "tag": "EUNE"},
    {"name": "wooback", "tag": "000"},
    {"name": "Albi", "tag": "Snoe2"},
    {"name": "tak čaaaaaau", "tag": "EUNE"},
    {"name": "miracle", "tag": "ahaha"},
    {"name": "LVR Operator", "tag": "AURA"},
    {"name": "holæhuro", "tag": "uwu"},
    {"name": "Aomine Daiki", "tag": "AMI"},
    {"name": "A G Ω N Y", "tag": "9999"},
    {"name": "LeagueOfLegends", "tag": "6529"},
    {"name": "Ruststalker", "tag": "EUNE"},
    {"name": "Mordecaay", "tag": "EUNE"},
    {"name": "xPigBenis", "tag": "7569"},
    {"name": "q Adc p", "tag": "jinx"},
    {"name": "Ketchup Heinz", "tag": "EUNE"},
    {"name": "Conqueror", "tag": "reall"},
    {"name": "Wanheda", "tag": "juss"},
    {"name": "TCA Phenomenal", "tag": "GChad"},
    {"name": "Zinc", "tag": "DA3C"},
    {"name": "bunny lover", "tag": "meow"},
    {"name": "sRAK0jad", "tag": "EUNE"},
    {"name": "Pete", "tag": "dev"},
    {"name": "UncleTwister", "tag": "EUNE"},
    {"name": "F1WKON1", "tag": "2U1"},
    {"name": "Asta Demon", "tag": "JJK"},
    {"name": "Blood Vessel", "tag": "EUNE"},
    {"name": "Smithereens", "tag": "777"},
    {"name": "Motanelu14", "tag": "EUNE"},
    {"name": "massurrowskyy", "tag": "EUNE"},
    {"name": "Iqushi", "tag": "meow"},
    {"name": "Velký Gatsby", "tag": "EUNE"},
    {"name": "a trecut vara", "tag": "CXF"},
    {"name": "Ersanole", "tag": "EUNE"},
    {"name": "Ninu", "tag": "EUNE"},
    {"name": "GrACZAQ", "tag": "sus"},
    {"name": "sorrymaker1", "tag": "EUNE"},
    {"name": "Milan Gatner", "tag": "EUNE"},
    {"name": "Mistsplitter", "tag": "Storm"},
    {"name": "Hi Im Yasuo Supp", "tag": "EUNE"},
    {"name": "The Simple 0ne", "tag": "EUNE"},
    {"name": "Outfox", "tag": "EUNE"},
    {"name": "StefanosAleksand", "tag": "EUNE"},
    {"name": "Saiyan", "tag": "EUNE1"},
    {"name": "T1 Kirito", "tag": "FAKER"},
    {"name": "lukk1exiao", "tag": "lukk"},
    {"name": "Brencis Dublis", "tag": "EUNE"},
    {"name": "Dark Rainbow", "tag": "EUNE"},
    {"name": "Tůmič", "tag": "EUNE"},
    {"name": "JotEmBea", "tag": "EUNE"},  #100
    {"name": "MłodyChillin420", "tag": "EUNE"},
    {"name": "Endless Wind", "tag": "1v9"},
    {"name": "COZI COSSACK", "tag": "ddx"},
    {"name": "JotEmBea", "tag": "EUNE"},
    {"name": "Hi Im Dahlia", "tag": "1337"},
    {"name": "RHS Pivkan", "tag": "EUNE"},
    {"name": "q Adc p", "tag": "jinx"},
    {"name": "RW Whipper", "tag": "RWs"},
    {"name": "Lethal Machine", "tag": "EUNE"},
    {"name": "happihappihappi", "tag": "cat"},
    {"name": "Pasożyd", "tag": "ACC04"},
    {"name": "2003szaniaahater", "tag": "LIPA"},
    {"name": "patryk", "tag": "jimmy"},
    {"name": "Căpitanul Nemo", "tag": "42069"},
    {"name": "StefanosAleksand", "tag": "EUNE"},
    {"name": "Miven", "tag": "EUNE"},
    {"name": "KvX Megachad", "tag": "bench"},
    {"name": "Legend Of Zoe", "tag": "Lawi"},
    {"name": "BEHEADER", "tag": "NIXU"},
    {"name": "GreeNMark", "tag": "EUNE"},
    {"name": "烤肉串", "tag": "420"},
    {"name": "Monks", "tag": "EUNE"},
    {"name": "Coatpustmain", "tag": "Main"},
    {"name": "Tômmy Shèlby", "tag": "EUNE"},
    {"name": "ReoNa", "tag": "SAO"},
    {"name": "PipelinePunch", "tag": "2137"},
    {"name": "Pyrtuch", "tag": "0020"},
    {"name": "F1WKON1", "tag": "2U1"},
    {"name": "GreEnTheBhoppeR", "tag": "green"},
    {"name": "la ahad", "tag": "007"},
    {"name": "A mumik", "tag": "MUMU"},
    {"name": "BTW Katus", "tag": "EUNE"},
    {"name": "Agrafa", "tag": "EUNE"},
    {"name": "CringeEuneDogsz", "tag": "EUNE"},
    {"name": "Μisfit", "tag": "EUNE"},
    {"name": "MATlŚ", "tag": "EUNE"},
    {"name": "AwetiS", "tag": "EUNE"},
    {"name": "Egirls Papa", "tag": "SNUDE"},
    {"name": "StEAL7hy", "tag": "00001"},
    {"name": "Minion", "tag": "1989"},
    {"name": "Policjant Kamil", "tag": "997"},
    {"name": "TAE Tiridus", "tag": "EUNE"},
    {"name": "Tentativez", "tag": "EUNE"},
    {"name": "Elora", "tag": "十十十"},
    {"name": "makemesushi", "tag": "pepuś"},
    {"name": "Kubvz", "tag": "EUNE"},
    {"name": "nbd", "tag": "xxxxx"},
    {"name": "Czystka Etniczna", "tag": "EUNE"},
    {"name": "Monkeyy D Talon", "tag": "EUNE"},
    {"name": "Prestigious Name", "tag": "EUNE"},
    {"name": "LVR Plague", "tag": "aura"},
    {"name": "Luxzor", "tag": "EUNE"},
    {"name": "Lithium", "tag": "eune2"},
    {"name": "dsahgdfs", "tag": "EUNE"},
    {"name": "danutzu", "tag": "thau"},
    {"name": "KUŘECÍ VE SLEVĚ", "tag": "LFW"},
    {"name": "T1 Onyong nyong", "tag": "EUNE"},
    {"name": "legbénábblolosHU", "tag": "EUNE"},
    {"name": "KhiyroDanzo", "tag": "EUNE"},
    {"name": "Acrozo", "tag": "0001"},
    {"name": "Atackator", "tag": "PEEP"},
    {"name": "Tomaszek", "tag": "EUNE"},
    {"name": "DoublePenetrate", "tag": "6969"},
    {"name": "中國代理", "tag": "CHN"},
    {"name": "Janina Dumna", "tag": "WOW"},
    {"name": "Wild Z3D", "tag": "MBT"},
    {"name": "Svinja Pig", "tag": "0000"},
    {"name": "Lachtann", "tag": "EUNE"},
    {"name": "Rank1 Ksante", "tag": "Top"},
    {"name": "Thryson", "tag": "BOMBA"},
    {"name": "Zrnič", "tag": "EUNE"},
    {"name": "Syrrex", "tag": "miju"},
    {"name": "Legancko", "tag": "EUNE"},
    {"name": "lukk1exiao", "tag": "lukk"},
    {"name": "SXY Catalin", "tag": "SXY"},
    {"name": "FlyingSalmon", "tag": "4444"},
    {"name": "Inkey", "tag": "FL123"},
    {"name": "Mill3r", "tag": "69696"},
    {"name": "misterek ostrowa", "tag": "3554"},
    {"name": "Party with ZAC", "tag": "ZAC"},
    {"name": "Aís", "tag": "EUNE"},
    {"name": "clown irl", "tag": "bomba"},
    {"name": "GrotStik", "tag": "XDDD"},
    {"name": "Horizon", "tag": "DSENT"},
    {"name": "Ąti", "tag": "EUNE"},
    {"name": "Ocsi", "tag": "EUNE"},
    {"name": "Samuraj", "tag": "1v9"},
    {"name": "play4funacc", "tag": "EUNE"},
    {"name": "dennis", "tag": "1D57"},
    {"name": "Zeri", "tag": "ZΕRI"},
    {"name": "Haversrác", "tag": "Ariel"},
    {"name": "TziN1uS", "tag": "EUNE"},
    {"name": "Mushishi", "tag": "404"},
    {"name": "everlasting love", "tag": "adri"},
    {"name": "Holly Molly", "tag": "9499"},
    {"name": "DRIPPING BLOOD", "tag": "FLOW"},
    {"name": "Hrišćanska žena", "tag": "BUREK"},
    {"name": "BRDHK 93 LPPK", "tag": "7612"},
    {"name": "hadusahdsaia", "tag": "ICY"},
    {"name": "YAHAYA ABDULLAHI", "tag": "CH1"}, #200
    {"name": "MatMar", "tag": "VOID"},
    {"name": "Lankku", "tag": "1PART"},
    {"name": "ImARealSmurfSoSU", "tag": "EUNE"},
    {"name": "Natrium", "tag": "808"},
    {"name": "Ntampi", "tag": "EUNE"},
    {"name": "1000Thoughts3Cig", "tag": "Left"},
    {"name": "asasinpuia", "tag": "EUNE"},
    {"name": "embrace μr pain", "tag": "death"},
    {"name": "I love u baby", "tag": "EUNE"},
    {"name": "º King Khada º", "tag": "BVITW"},
    {"name": "ale nudy hehe", "tag": "EUNE"},
    {"name": "MrUnknoωn", "tag": "EUNE"},
    {"name": "Salniel", "tag": "EUNE"},
    {"name": "ALIEN66620", "tag": "EUNE"},
    {"name": "Depressed Water", "tag": "FF15"},
    {"name": "Vızsla", "tag": "4444"},
    {"name": "Cotton", "tag": "poor"},
    {"name": "bot is supp gap", "tag": "EUNE"},
    {"name": "BALKAN TERR0RIST", "tag": "AXES"},
    {"name": "Dadinho", "tag": "Sera"},
    {"name": "AxmarDe", "tag": "1222"},
    {"name": "InceputDeSfarsit", "tag": "SibiX"},
    {"name": "Erlija", "tag": "EUNE"},
    {"name": "Aceelion", "tag": "EUNE"},
    {"name": "Ahru", "tag": "EUNE"},
    {"name": "angelopulos", "tag": "liker"},
    {"name": "HorvyGreuDeUcys", "tag": "David"},
    {"name": "ease your mind", "tag": "5727"},
    {"name": "Monopolista", "tag": "2175"},
    {"name": "szymek2502", "tag": "8621"},
    {"name": "Waridier", "tag": "EUNE"},
    {"name": "KPOP Enjoyer", "tag": "Orii"},
    {"name": "NSN Adu", "tag": "NSN"},
    {"name": "Kamiś", "tag": "UwUś"},
    {"name": "tușa", "tag": "9174"},
    {"name": "xWhatsUpx", "tag": "EUNE"},
    {"name": "Atasor", "tag": "EUNE"},
    {"name": "Picus z lesa", "tag": "EUNE"},
    {"name": "Catalinu01", "tag": "2001"},
    {"name": "Syllvanas", "tag": "EUN"},
    {"name": "FrozenTomb", "tag": "Cold"},
    {"name": "SÇ4RL0RÐ", "tag": "GR3C0"},
    {"name": "Critlyn", "tag": "King"},
    {"name": "Diligis4Ever", "tag": "Ever"},
    {"name": "MANlEK", "tag": "EUNE"},
    {"name": "Stardust", "tag": "アニメ"},
    {"name": "VoGterr", "tag": "1369"},
    {"name": "TSE Xenolith", "tag": "0000"},
    {"name": "Hunter Senpai", "tag": "EUNE"},
    {"name": "Chat Warrior", "tag": "EUNE"},
    {"name": "Hellon", "tag": "EUNE"},
    {"name": "bnc", "tag": "bence"},
    {"name": "Alhaitham", "tag": "9874"},
    {"name": "Reci", "tag": "EUNE"},
    {"name": "KillerŠkrat69", "tag": "EUNE"},
    {"name": "Venom", "tag": "RXG7"},
    {"name": "BowDownToTheKing", "tag": "EUNE"},
    {"name": "Flicker Gooner", "tag": "sinia"},
    {"name": "Kookeri", "tag": "Bombo"},
    {"name": "esq13", "tag": "EUNE"},
    {"name": "396907435729", "tag": "EUNE"},
    {"name": "Zedraw", "tag": "pisu"},
    {"name": "MarselW", "tag": "Devil"},
    {"name": "hapsibol", "tag": "kox"},
    {"name": "galaxyViced", "tag": "EUNE"},
    {"name": "MOTOmishleto", "tag": "6969"},
    {"name": "Děsire", "tag": "2312"},
    {"name": "Corruption", "tag": "123s"},
    {"name": "Bezo", "tag": "EUNE"},
    {"name": "Arbalezt", "tag": "EUNE"},
    {"name": "ZUG Pan elektryk", "tag": "chooj"},
    {"name": "SamooKata69", "tag": "EUNE"},
    {"name": "Solo Queue King", "tag": "EUNE"},
    {"name": "GreekButcher1", "tag": "EUNE"},
    {"name": "Tökgyalu", "tag": "GAY"},
    {"name": "JustYourBoss", "tag": "EUNE"},
    {"name": "DrSkilla", "tag": "AEC"},
    {"name": "F3nikz", "tag": "EUNE"},
    {"name": "CrankZ", "tag": "LDMP"},
    {"name": "Silent", "tag": "EUNE1"},
    {"name": "Sun Hashira", "tag": "EUNE"},
    {"name": "Borek", "tag": "Brek"},
    {"name": "primačica", "tag": "qrca"},
    {"name": "KSIPNA ELLIN", "tag": "EUNE"},
    {"name": "Belicius", "tag": "Yami"},
    {"name": "Seb", "tag": "npseb"},
    {"name": "May2Bee", "tag": "EUNE"},
    {"name": "Mood", "tag": "Rings"},
    {"name": "Z1pp0", "tag": "EUNE"},
    {"name": "silwestor", "tag": "EUNE"},
    {"name": "Johnny Troxes", "tag": "EUNE"},
    {"name": "Etherslay", "tag": "66666"},
    {"name": "Carry IRL", "tag": "EUNE1"},
    {"name": "oro na rurach", "tag": "EUNE"},
    {"name": "Marianeu", "tag": "2137"},
    {"name": "AnteQ7", "tag": "EUNE"},
    {"name": "Feta", "tag": "janna"},
    {"name": "Avares", "tag": "HWEI"},
    {"name": "ωrednα suκα", "tag": "suκα"},
    {"name": "AlessiOG", "tag": "6969"}, #300
    {"name": "ROIT", "tag": "420"},
    {"name": "Bel Vader", "tag": "VOID"},
    {"name": "LVR Operator", "tag": "AURA"},
    {"name": "brunchi4", "tag": "EUNE"},
    {"name": "Demacian Traitor", "tag": "EUNE"},
    {"name": "Ciorbă de zgâți", "tag": "seex"},
    {"name": "Gruby Kotlet", "tag": "PYRY"},
    {"name": "OCB Stfn", "tag": "1323"},
    {"name": "shimbinbimbin", "tag": "EUN"},
    {"name": "Klakson1337", "tag": "SUSSY"},
    {"name": "one day maybe", "tag": "RIVEN"},
    {"name": "VanHellsing7", "tag": "van"},
    {"name": "Szakin", "tag": "2137"},
    {"name": "Dusk", "tag": "DSENT"},
    {"name": "Yuval", "tag": "EUNE"},
    {"name": "Kounelodrakos", "tag": "0000"},
    {"name": "RadioactiveLemon", "tag": "JINX"},
    {"name": "Indica pref", "tag": "0007"},
    {"name": "0SK4R1", "tag": "EUNE"},
    {"name": "BabuDzeki", "tag": "777"},
    {"name": "Xeltol", "tag": "G59"},
    {"name": "ßorenêo", "tag": "EUNE"},
    {"name": "Đr Trolli", "tag": "2115"},
    {"name": "Τ1 Fαker", "tag": "EUNE"},
    {"name": "Алекса", "tag": "am10"},
    {"name": "NER0IDE", "tag": "RAT"},
    {"name": "I Love Vandalizm", "tag": "ILV"},
    {"name": "GGIzIWiNlol", "tag": "EUNE"},
    {"name": "JãyceBond", "tag": "2137"},
    {"name": "Noname SL", "tag": "SUPP"},
    {"name": "V X D", "tag": "GTR35"},
    {"name": "mehur", "tag": "rank2"},
    {"name": "Sazos iOwNz", "tag": "EUNE"},
    {"name": "Kayle Kayden", "tag": "EUNE"},
    {"name": "Tashu", "tag": "000"},
    {"name": "NGL Im Reformed", "tag": "Sike"},
    {"name": "AquaPearls", "tag": "EUNE"},
    {"name": "PepePopoCheck", "tag": "SZESE"},
    {"name": "pjay", "tag": "6733"},
    {"name": "jej tatuś", "tag": "EUNE"},
    {"name": "xKanelen", "tag": "HAU"},
    {"name": "yesnoyesno", "tag": "EUNE"},
    {"name": "Demon Of Secrets", "tag": "Swain"},
    {"name": "Doktor Nauk", "tag": "PhD"},
    {"name": "EpicMidLane", "tag": "EUNE"},
    {"name": "tehkon", "tag": "EUNE"},
    {"name": "nic nie ma sensu", "tag": "maru"},
    {"name": "KorShack", "tag": "6666"},
    {"name": "Bulion Bojowy", "tag": "EUNE"},
    {"name": "Mirciu", "tag": "GYM"},
    {"name": "Čuspic nešlo nic", "tag": "6969"},
    {"name": "blurred", "tag": "0000"},
    {"name": "Ryan Gosling", "tag": "4354"},
    {"name": "Øceløtte", "tag": "EUNE"},
    {"name": "Juru", "tag": "EzEz"},
    {"name": "Paradox", "tag": "Moon"},
    {"name": "ekko", "tag": "god69"},
    {"name": "radoneko", "tag": "EUNE"},
    {"name": "Flake", "tag": "FL4K3"},
    {"name": "Necruso", "tag": "00001"},
    {"name": "TarxiδiaTouMakh", "tag": "EUNE"},
    {"name": "aLittle mouse", "tag": "GEJ"},
    {"name": "q9e", "tag": "xxx"},
    {"name": "Zhaywtur", "tag": "EUNE"},
    {"name": "klisotr", "tag": "EUNE"},
    {"name": "Empréss Of Ixtál", "tag": "EUNE"},
    {"name": "Mεlεγs", "tag": "miu"},
    {"name": "his selena", "tag": "0077"},
    {"name": "KumKiš", "tag": "031"},
    {"name": "Hirlne", "tag": "EUNE"},
    {"name": "Unishtojitelq", "tag": "topg"},
    {"name": "xSnecio", "tag": "EUNE"},
    {"name": "YaBoiBaja", "tag": "2090"},
    {"name": "Corgimancer", "tag": "EUNE"},
    {"name": "nerves player", "tag": "SZLUG"},
    {"name": "better than her", "tag": "1975"},
    {"name": "Carryeramite", "tag": "EUNE"},
    {"name": "Jet7777", "tag": "DSune"},
    {"name": "trickeR", "tag": "RNG"},
    {"name": "Loathe", "tag": "busy"},
    {"name": "Ðestiny", "tag": "Forge"},
    {"name": "Ilegitim", "tag": "0001"},
    {"name": "MaZeR", "tag": "SSR"},
    {"name": "SNOWBAAAAAAAALL", "tag": "EUNE"},
    {"name": "Pan Kakauko", "tag": "PWWP"},
    {"name": "Techno", "tag": "CUCK"},
    {"name": "Kasuny", "tag": "6969"},
    {"name": "JgDIff", "tag": "0202"},
    {"name": "rWilth", "tag": "777"},
    {"name": "luka nigović", "tag": "EUNE"},
    {"name": "CBK Cappy", "tag": "BOSO"},
    {"name": "Beauty", "tag": "1191"},
    {"name": "SpArTaNuS", "tag": "JAPAN"},
    {"name": "Luminosity", "tag": "EUNE"},
    {"name": "BillTheBull", "tag": "LBJ23"},
    {"name": "Zilder", "tag": "TND3B"},
    {"name": "Bercik", "tag": "23901"},
    {"name": "Dong Master", "tag": "DONG"},
    {"name": "BobsledBilly", "tag": "001"},
    {"name": "lecSack", "tag": "amsen"}, #400
    {"name": "ΠΟΛΥΕΛΑΙΟΣ", "tag": "7777"},
    {"name": "Whangdoodle", "tag": "EUNE"},
    {"name": "Dominús", "tag": "adc"},
    {"name": "BacoSS Ultracfel", "tag": "EUNE"},
    {"name": "high off life", "tag": "2222"},
    {"name": "Disco Jakubek", "tag": "xpp"},
    {"name": "gabisinge66", "tag": "EUNE"},
    {"name": "pablo cocos", "tag": "1956"},
    {"name": "ChosenOfTheStorm", "tag": "jggap"},
    {"name": "Pablo Escobard", "tag": "cox"},
    {"name": "Plazma", "tag": "keks"},
    {"name": "Forrest Pump", "tag": "EUNE"},
    {"name": "Predict", "tag": "EUNE1"},
    {"name": "C0CAL0CA", "tag": "EUNE"},
    {"name": "SirErőspista", "tag": "EUNE"},
    {"name": "Mind Architect", "tag": "TAG"},
    {"name": "ÄŇÐRÈW", "tag": "EUNE"},
    {"name": "Bystry", "tag": "Jinx"},
    {"name": "Xerdzio", "tag": "EUNE"},
    {"name": "DοminοJachas", "tag": "jas"},
    {"name": "Kyrie Irving", "tag": "4422"},
    {"name": "SP1Nx", "tag": "OR1ON"},
    {"name": "Matyas999", "tag": "1506"},
    {"name": "Spocenmen", "tag": "8351"},
    {"name": "Sumprdka", "tag": "PcDěd"},
    {"name": "Don Pollo", "tag": "272"},
    {"name": "trexa adi trexa", "tag": "EUNE"},
    {"name": "SpoconyKarzeł", "tag": "EUNE"},
    {"name": "NugetRane", "tag": "EUNE"},
    {"name": "Stanisław", "tag": "stach"},
    {"name": "Siwiec", "tag": "Fufu"},
    {"name": "Paffs", "tag": "EUNE"},
    {"name": "Bolek04", "tag": "RKS"},
    {"name": "Ward The Bush", "tag": "EUNE"},
    {"name": "REGELE SEXULUI", "tag": "DIDDY"},
    {"name": "7777777777777777", "tag": "BXR"},
    {"name": "kublot8", "tag": "EUNE"},
    {"name": "Valar Morghulis", "tag": "BINKA"},
    {"name": "D3D4", "tag": "ZYZZ"},
    {"name": "yeahh", "tag": "EUNE"},
    {"name": "PDFK LelekoZ", "tag": "123"},
    {"name": "Shizo", "tag": "3742"},
    {"name": "CroPhazer", "tag": "9CM"},
    {"name": "krig cursvalutar", "tag": "133"},
    {"name": "VεryGoodSupport", "tag": "77777"},
    {"name": "light your brain", "tag": "EUNE"},
    {"name": "fleeting dreams", "tag": "黄泉の国"},
    {"name": "tozzi123456789", "tag": "EUNE"},
    {"name": "DreadŁord", "tag": "EUNE"},
    {"name": "dont give up", "tag": "hope"},
    {"name": "K E L A M", "tag": "0808"},
    {"name": "Tramc", "tag": "EUNE"},
    {"name": "ΕΝΟΧΛΗΤΙΚΟΣ", "tag": "BOMBA"},
    {"name": "Zartiee", "tag": "MEOW"},
    {"name": "King Bobo", "tag": "662"},
    {"name": "Chase Zed", "tag": "EUNE"},
    {"name": "I Will Top Lane", "tag": "EUNE"},
    {"name": "Pyllykarva123", "tag": "EUNE"},
    {"name": "NightDrogon", "tag": "EUNE"},
    {"name": "jeisan born", "tag": "EUNE"},
    {"name": "Quincy Promes", "tag": "EUN"},
    {"name": "2madd713", "tag": "713"},
    {"name": "Dejmon Targaryen", "tag": "EUNE"},
    {"name": "Tovan", "tag": "EUNE"},
    {"name": "5 Stackuri", "tag": "mason"},
    {"name": "Just Michael", "tag": "LMFAO"},
    {"name": "Drumel", "tag": "EUNE"},
    {"name": "rat", "tag": "bode"},
    {"name": "Sandža", "tag": "PEDRO"},
    {"name": "RIP top4e05", "tag": "CSX"},
    {"name": "Weakside Refugee", "tag": "EUNE"},
    {"name": "LokoFloko", "tag": "EUNE"},
    {"name": "feel like china", "tag": "CHC"},
    {"name": "Karyu No Hoko", "tag": "EUNE"},
    {"name": "SSH root", "tag": "EUNE"},
    {"name": "Sicva", "tag": "essa"},
    {"name": "BlackShadow", "tag": "BSLRY"},
    {"name": "Dany", "tag": "0204"},
    {"name": "Hrsyk", "tag": "Witch"},
    {"name": "Skorstein", "tag": "EUNE"},
    {"name": "julia biedronka", "tag": "GYAT"},
    {"name": "Voiga", "tag": "EUNE"},
    {"name": "metq", "tag": "EUNE"},
    {"name": "you dog not me", "tag": "ceyns"},
    {"name": "DyslexicGinger", "tag": "BLM"},
    {"name": "CweIuś", "tag": "2137"},
    {"name": "mgr Filip K", "tag": "EUNE"},
    {"name": "MishanD", "tag": "EUNE"},
    {"name": "WiewiurkaPL", "tag": "ARAM"},
    {"name": "Arezir", "tag": "EUNE"},
    {"name": "maciejek69pl", "tag": "dupa"},
    {"name": "lewy", "tag": "1235"},
    {"name": "Dime", "tag": "7D2"},
    {"name": "Tofi", "tag": "soju"},
    {"name": "Romanians Slayer", "tag": "escu"},
    {"name": "Z I", "tag": "first"},
    {"name": "Celestial Draco", "tag": "EUNE"},
    {"name": "I W À Y", "tag": "EUNE"},
    {"name": "Nicram", "tag": "EUNE"},
    {"name": "Rögan", "tag": "EUNE"} #500
]










